def iso_8859_8_decoder(string: str):
    string = string.replace('\\xe0', 'א')
    string = string.replace('\\xe1', 'ב')
    string = string.replace('\\xe2', 'ג')
    string = string.replace('\\xe3', 'ד')
    string = string.replace('\\xe4', 'ה')
    string = string.replace('\\xe5', 'ו')
    string = string.replace('\\xe6', 'ז')
    string = string.replace('\\xe7', 'ח')
    string = string.replace('\\xe8', 'ט')
    string = string.replace('\\xe9', 'י')

    string = string.replace('\\xea', 'ך')
    string = string.replace('\\xeb', 'כ')
    string = string.replace('\\xec', 'ל')
    string = string.replace('\\xed', 'ם')
    string = string.replace('\\xee', 'מ')
    string = string.replace('\\xef', 'ן')

    string = string.replace('\\xf0', 'נ')
    string = string.replace('\\xf1', 'ס')
    string = string.replace('\\xf2', 'ע')
    string = string.replace('\\xf3', 'ף')
    string = string.replace('\\xf4', 'פ')
    string = string.replace('\\xf5', 'ץ')
    string = string.replace('\\xf6', 'צ')
    string = string.replace('\\xf7', 'ק')
    string = string.replace('\\xf8', 'ר')
    string = string.replace('\\xf9', 'ש')
    string = string.replace('\\xfa', 'ת')
    # other
    string = string.replace('&nbsp;', ' ')
    return string


def iso_8859_8_encoder(string: str):
    string = string.replace('א', '\\xe0')
    string = string.replace('ב', '\\xe1')
    string = string.replace('ג', '\\xe2')
    string = string.replace('ד', '\\xe3')
    string = string.replace('ה', '\\xe4')
    string = string.replace('ו', '\\xe5')
    string = string.replace('ז', '\\xe6')
    string = string.replace('ח', '\\xe7')
    string = string.replace('ט', '\\xe8')
    string = string.replace('י', '\\xe9')

    string = string.replace('ך', '\\xea')
    string = string.replace('כ', '\\xeb')
    string = string.replace('ל', '\\xec')
    string = string.replace('ם', '\\xed')
    string = string.replace('מ', '\\xee')
    string = string.replace('ן', '\\xef')

    string = string.replace('נ', '\\xf0')
    string = string.replace('ס', '\\xf1')
    string = string.replace('ע', '\\xf2')
    string = string.replace('ף', '\\xf3')
    string = string.replace('פ', '\\xf4')
    string = string.replace('ץ', '\\xf5')
    string = string.replace('צ', '\\xf6')
    string = string.replace('ק', '\\xf7')
    string = string.replace('ר', '\\xf8')
    string = string.replace('ש', '\\xf9')
    string = string.replace('ת', '\\xfa')
    # other
    string = string.replace(' ', '&nbsp;')
    return string
